# Generated by Django 2.2.2 on 2019-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promised_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
